library(shiny)
shinyUI(fluidPage(
      titlePanel("Let my algorithm try to guess if you are a Christian."),
      br(),
      p("Answer the following questions, and my algorithm
        will try to predict whether or not you're Christian.  It is 89% accurate."),  
      p("The algorithm -- logistic regression --  was trained and tested on a dataset of 35,071 phone survey responses, conducted by the Pew Research Center as part of the 2014 U.S. Religious Landscape Study."),
      em("DISCLAIMER: \"Pew Research Center bears no responsibility for the interpretations presented or conclusions reached based on analysis of the data.\"  And in general this app is not meant to be taken seriously.  If you have questions, contact me at: luke.wolcott@gmail.com."),
      hr(),
      p("When you've chosen your responses, hit SUBMIT.  Until you answer every question, you'll get a funky error."),
      selectInput("qa1", "Generally, how would you say things are these days in your life – would you say that you are very happy, pretty happy, or not too happy?",
      		  choices = c("(Select one)","Very happy", "Pretty happy", "Not too happy", "(VOL) Don't know/Refused")),
      selectInput("qi4a", "Now, thinking about some different kinds of experiences, how often do you: (a) ...feel a deep sense of spiritual peace and well-being?",
                  choices = c("(Select one)","At least once a week", "Once or twice a month", 
                              "Several times a year", "Seldom", "Never", "(VOL) Don't Know/Refused")),
      selectInput("qi4b", "(b) ...feel a deep sense of wonder about the universe?",
      	          choices = c("(Select one)","At least once a week", "Once or twice a month", 
                              "Several times a year", "Seldom", "Never", "(VOL) Don't Know/Refused")),
      selectInput("qi4c", "(c) ...feel a strong sense of gratitude or thankfulness?",
      	          choices = c("(Select one)","At least once a week", "Once or twice a month", 
                              "Several times a year", "Seldom", "Never", "(VOL) Don't Know/Refused")),
      selectInput("qi4d", "(d) ...think about the meaning and purpose of life?",
      	          choices = c("(Select one)","At least once a week", "Once or twice a month", 
                              "Several times a year", "Seldom", "Never", "(VOL) Don't Know/Refused")),
      selectInput("qm5a", "As you read these statements about churches and other religious organizations, please indicate if you agree or disagree with each one.  Churches and other religious organizations: (a) ...focus too much on rules.",
                  choices = c("(Select one)","Agree", "DISagree", "(VOL) Don't know/Refused")),
      selectInput("qm5b", "(b) ...are too concerned with money and power.",
                  choices = c("(Select one)","Agree", "DISagree", "(VOL) Don't know/Refused")),
      selectInput("qm5d", "(d) ...are too involved with politics.",
                  choices = c("(Select one)","Agree", "DISagree", "(VOL) Don't know/Refused")),
      selectInput("qm5e", "(e) ...protect and strengthen morality in society.",
                  choices = c("(Select one)","Agree", "DISagree", "(VOL) Don't know/Refused")),
      selectInput("qm5f", "(f) ...bring people together and strengthen community bonds.",
                  choices = c("(Select one)","Agree", "DISagree", "(VOL) Don't know/Refused")),
      selectInput("qm5g", "(g) ...play an important role in helping the poor and needy.",
                  choices = c("(Select one)","Agree", "DISagree", "(VOL) Don't know/Refused")),
      selectInput("KEPTREL", "True or False: Your current religious affiliation (if any) is THE SAME AS the religious affiliation (if any) that you were raised with.  For this question, restrict to the following six affiliations: Christian, Muslim, Jewish, Buddhist, Other, None.", choices = c("(Select one)","TRUE", "FALSE")),
      strong("Here are some demographic questions."),
      selectInput("agerec", "What is your age?",
                  choices = c("(Select one)","Age 24 or younger", "Age 25-29", "30-34", "35-39", "40-44",
		  "45-49", "50-54", "55-59", "60-64", "65-69", "70-74", "75-79", "80-84",
		  "85-89", "Age 90 or older", "Don't know/refused")),
      selectInput("educ", "What is the highest level of school you have completed or the highest degree you have received?",
                  choices = c("(Select one)","Less than high school (Grades 1-8 or no formal schooling)",
		  "High school incomplete (Grades 9-11 or Grade 12 with NO diploma)",
		  "High school graduate (Grade 12 with diploma or GED certificate)",
		  "Some college, no degree (includes some community college)",
		  "Two year associate degree from a college or university",
		  "Four year college or university degree/Bachelor's degree (e.g., BS, BA, AB)",
		  "Some postgraduate or professional schooling, no postgraduate degree (e.g. some graduate school)",
		  "Postgraduate or professional degree, including master's, doctorate, medical or law degree (e.g., MA, MS, PhD, MD...)")),
      selectInput("income", "Last year, what was your total family income from all sources, before taxes?",
                  choices = c("(Select one)","Less than $10,000", "10 to under $20,000", "20 to under $30,000",
		  "30 to under $40,000", "40 to under $50,000", "50 to under $75,000",
		  "75 to under $100,000", "100 to under $150,000", "$150,000 or more",
		  "(VOL) Don't know/Refused")),
      selectInput("party", "In politics today, do you consider yourself a Republican, Democrat, or Independent?",
                  choices = c("(Select one)","Republican", "Democrat", "Independent", "(VOL) No preference",
		  "(VOL) Other party", "(VOL) Don't know/Refused")),
      selectInput("ideo", "In general, would you describe your political views as...",
                  choices = c("(Select one)","Very conservative", "Conservative", "Moderate", "Liberal, OR",
		  "Very liberal?", "(VOL) Don't know/Refused")),
      selectInput("SEX", "Are you male or female?", choices = c("(Select one)","Male", "Female")),
      submitButton("SUBMIT"),
      br(),
      p("My algorithm says that you are:"),
      textOutput("religion"),
      br(),
      hr()
      )
)


